# Generated by Django 4.2 on 2023-04-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_reason', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=15)),
                ('product_price', models.IntegerField()),
                ('color_type', models.CharField(max_length=100)),
                ('yarn_type', models.CharField(max_length=100)),
                ('yarn_count', models.IntegerField()),
                ('brand', models.CharField(max_length=30)),
                ('product_in_stock', models.BooleanField(default=True)),
                ('product_tags', models.CharField(max_length=300)),
                ('product_primary_image', models.ImageField(upload_to='product_primary_images/')),
                ('product_more_information', models.CharField(max_length=200)),
                ('product_search_keyword', models.CharField(max_length=400)),
                ('on_discount', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('discount_expiry', models.DateTimeField(blank=True, null=True)),
                ('discount_reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.discountreason')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_items', models.CharField(max_length=100)),
                ('wisher_person_ip', models.GenericIPAddressField()),
                ('wisher_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image_alt_tag', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.UUIDField(auto_created=True)),
                ('cart_items', models.CharField(max_length=400)),
                ('cart_person_ip', models.GenericIPAddressField()),
                ('cart_items_price', models.IntegerField()),
                ('cart_added_date', models.DateTimeField(auto_now_add=True)),
                ('cart_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
