# Generated by Django 4.2 on 2023-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wish_count',
            field=models.IntegerField(default=0),
        ),
    ]
