# Generated by Django 4.2 on 2023-04-19 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_wishlist_wisher_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
