# Generated by Django 4.2 on 2023-04-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_wishlist_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='add_date',
        ),
    ]
