# Generated by Django 4.2 on 2023-04-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_items_prices_order_order_items_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items_sizes',
            field=models.CharField(default=[1, 2, 3], max_length=400),
            preserve_default=False,
        ),
    ]
