# Generated by Django 4.2 on 2023-04-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(default=10000000)),
            ],
        ),
    ]
