# Generated by Django 4.2 on 2023-04-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderid_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items_prices',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items_sizes',
        ),
    ]
