# Generated by Django 4.2 on 2023-04-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_order_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_person_email',
            field=models.EmailField(default='hello@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_person_ip',
            field=models.GenericIPAddressField(default='1313'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(),
        ),
    ]
